# ===============================
# STAGE 1 — BUILD THE REACT APP
# ===============================
FROM node:20-alpine AS builder

WORKDIR /app

# CRITICAL FIX 1: Install build tools and headers required for native module compilation
# These packages provide g++, make, python, and linux headers (like libudev.h) needed by node-gyp.
RUN apk add --no-cache python3 make g++ linux-headers eudev-dev

# Copy package.json + lockfile (lockfile pre-generated by buildspec)
COPY package.json package-lock.json ./

# CRITICAL FIX 2: Install dependencies
# We use '--legacy-peer-deps' to prevent the ERESOLVE peer dependency conflicts.
RUN npm install --legacy-peer-deps

# Copy the rest of the source code
COPY . .

# Build production bundle
RUN npm run build


# ===============================
# STAGE 2 — NGINX SERVER
# ===============================
FROM nginx:stable-alpine AS production

# Clean nginx folder
RUN rm -rf /usr/share/nginx/html/*

# Copy built assets
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]